# Generated by Django 4.0 on 2022-01-07 22:53

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('url', models.TextField(null=True)),
                ('user_description', models.TextField(null=True)),
                ('user_label', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('slug', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('parent', models.TextField(null=True)),
                ('posted_date', models.DateTimeField(null=True)),
                ('username', models.TextField(null=True)),
                ('platform', models.TextField(null=True)),
                ('subreddit', models.TextField(null=True)),
                ('source', models.TextField(null=True)),
                ('post_id', models.TextField(null=True)),
                ('content_type', models.TextField(null=True)),
                ('kids', models.TextField(null=True)),
                ('post_link_title', models.TextField(null=True)),
                ('post_link_url', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('num_comments', models.IntegerField(null=True)),
                ('soundex', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.TextField(null=True)),
                ('user_id', models.TextField(null=True)),
                ('user_created', models.DateTimeField(null=True)),
                ('reply_count', models.TextField(null=True)),
                ('like_count', models.TextField(null=True)),
                ('mentioned_users', models.TextField(null=True)),
                ('followers', models.TextField(null=True)),
                ('qa', models.TextField(null=True)),
                ('score_last_updated', models.DateTimeField(null=True)),
                ('descendants', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='api_comment_search__fc7d6c_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('source', 'post_id')},
        ),
    ]
